In [15]:
x = [6.3,8.4,8.6,8.9,9.1,9.4,8.9,8.4,8.1,7.9,7.7,7.4,6.7,8.7,7.8]
len(x)

15

In [16]:
y = [14.2,12,10.2,8.5,3.2,3.2,1.8,2.6,2.6,2.6,4.4,4.7,4.7,3.3,2.4]
len(y)

15

In [17]:
import numpy as np

from sklearn.linear_model import LinearRegression

In [18]:
x_in = np.array(x).reshape(-1, 1)
y_in = np.array(y).reshape(-1, 1)

In [19]:
reg = LinearRegression().fit(x_in, y_in)

In [21]:
from sklearn.metrics import mean_squared_error

y_true = y
y_pred = reg.predict(x_in)
y_pred

array([[8.07277826],
       [4.99894678],
       [4.70620092],
       [4.26708214],
       [3.97433628],
       [3.5352175 ],
       [4.26708214],
       [4.99894678],
       [5.43806556],
       [5.73081142],
       [6.02355727],
       [6.46267606],
       [7.48728655],
       [4.55982799],
       [5.87718435]])

In [22]:
mean_squared_error(y_true, y_pred)

12.817128463999333

In [23]:
reg.coef_

array([[-1.46372928]])

In [ ]:
# 지역별 공실률을 선형 회귀로 푸는 것은 지역차에 대한 고려가 없어서 그런지 rmse가 너무 높았음.

In [25]:
import csv
 
f = open(r'C:\Users\soonw\Downloads\r_one_emp_rate_csv.csv', 'r', encoding='utf-8')
rdr = csv.reader(f)
for line in rdr:
    print(line)
f.close()    

['', '2013년 01분기', '2013년 02분기', '2013년 03분기', '2013년 04분기', '2014년 01분기', '2014년 02분기', '2014년 03분기', '2014년 04분기', '2015년 01분기', '2015년 02분기', '2015년 03분기', '2015년 04분기', '2016년 01분기', '2016년 02분기', '2016년 03분기', '2016년 04분기', '2017년 01분기', '2017년 02분기', '2017년 03분기', '2017년 04분기', '2018년 01분기', '2018년 02분기', '2018년 03분기', '2018년 04분기', '2019년 01분기', '2019년 02분기', '2019년 03분기', '2019년 04분기', '2020년 01분기', '2020년 02분기', '2020년 03분기']
['전체', '8.5', '8.8', '9.3', '10.7', '11.1', '12.2', '12.6', '12.7', '13.5', '12.7', '12.6', '13', '13.4', '13.4', '13', '13', '11.5', '12.4', '12', '11.9', '12.7', '13.2', '12.7', '12.4', '12.4', '12', '11.8', '11.5', '11.1', '11.3', '11.2']
['서울', '6.2', '6.4', '6.8', '8.4', '8.9', '10.4', '10.4', '10.8', '12', '10.2', '10.1', '10.2', '10.1', '10.2', '9.4', '9.4', '9.8', '11.3', '10.9', '10.5', '11.9', '12.1', '11.6', '11.4', '11', '10.2', '9.8', '9.1', '8.6', '9.1', '8.9']
['도심', '6.2', '6.8', '7.1', '7.7', '8.2', '12.2', '12.6', '14.1', '13.4', '11.1',

In [65]:
import pandas as pd

emp_rate = pd.read_csv(r'C:\Users\soonw\Downloads\r_one_emp_rate_csv.csv')
emp_rate

Unnamed: 0  2013년 01분기  2013년 02분기  2013년 03분기  2013년 04분기  2014년 01분기  \
0          전체         8.5         8.8         9.3        10.7        11.1   
1          서울         6.2         6.4         6.8         8.4         8.9   
2          도심         6.2         6.8         7.1         7.7         8.2   
3         광화문         4.6         4.9         5.1         7.0         7.8   
4         동대문         5.2         4.6         4.9         5.4         6.2   
5          명동         5.9         6.6         6.8         6.8         7.4   
6          시청         NaN         NaN         NaN         NaN         NaN   
7         을지로         NaN         NaN         NaN         NaN         NaN   
8         남대문         NaN         NaN         NaN         NaN         NaN   
9         서울역         1.4         1.5         2.1         2.6         2.5   
10         종로        10.1         9.9        10.0        10.5        11.0   
11        충무로        12.0        19.0        19.0        18.5        18.5   
12         강남         5.9         6.2         6.9         9.7        10.1   
13       강남대로         8.8        10.1         8.5        12.2        12.8   
14        논현역         NaN         NaN         NaN         NaN         NaN   
15       도산대로         5.5         6.6         8.5         8.3         8.7   
16         서초         6.1         5.1         5.6         7.9         7.7   
17         신사         2.8         3.0         3.0         4.7         4.6   
18       테헤란로         5.7         5.9         7.2        10.4        10.9   
19      여의도마포         6.2         5.6         5.7         7.1         8.0   
20        공덕역         0.9         0.8         0.8         0.1         3.2   
21        여의도         6.6         6.1         6.2         8.5         8.8   
22        영등포        10.5         9.4         9.3         9.5        10.2   
23         기타         5.4         6.8         7.3         9.5        10.2   
24         목동         3.0         3.8         3.4         4.2         4.9   
25         사당         2.5         3.1         3.1         5.1         4.8   
26         용산         4.7         5.0         6.2        10.7        10.5   
27         잠실         2.7         7.6         7.9         7.6         6.3   
28        장안동        13.7        13.7        13.7        18.1        18.1   
29         천호         7.0         7.6         7.9        15.4        15.7   
30       홍대합정         7.3         7.3        10.0         9.2         9.8   
31         화곡        10.0        11.8        11.5        11.5        21.1   

    2014년 02분기  2014년 03분기  2014년 04분기  2015년 01분기  ...  2018년 02분기  \
0         12.2        12.6        12.7        13.5  ...        13.2   
1         10.4        10.4        10.8        12.0  ...        12.1   
2         12.2        12.6        14.1        13.4  ...        15.6   
3          7.1         6.0         4.3         4.8  ...         7.9   
4          7.4         8.7         9.3         5.4  ...         8.4   
5          7.6        12.9        11.4        10.5  ...         9.3   
6          NaN         NaN         NaN         NaN  ...         NaN   
7          NaN         NaN         NaN         NaN  ...         NaN   
8          NaN         NaN         NaN         NaN  ...         NaN   
9         21.8        21.0        31.1        30.7  ...        14.4   
10        10.8        10.8        10.1         9.4  ...        21.4   
11        18.8        19.6        20.3        18.9  ...        16.9   
12        10.1        10.3        10.1        10.6  ...         9.4   
13        13.0        11.1        11.3        14.3  ...        19.9   
14         NaN         NaN         NaN         NaN  ...         3.2   
15        11.8        14.0        11.4        12.0  ...         7.9   
16         7.6         7.5         6.3        10.0  ...        11.2   
17         5.1         8.5         9.2         6.8  ...         7.0   
18        10.6        10.7        10.8        10.4  ...         7.7   
19         8.7         8.7         8.4   

In [66]:
a = emp_rate.drop(['Unnamed: 0'], axis=1)

In [67]:
a

2013년 01분기  2013년 02분기  2013년 03분기  2013년 04분기  2014년 01분기  2014년 02분기  \
0          8.5         8.8         9.3        10.7        11.1        12.2   
1          6.2         6.4         6.8         8.4         8.9        10.4   
2          6.2         6.8         7.1         7.7         8.2        12.2   
3          4.6         4.9         5.1         7.0         7.8         7.1   
4          5.2         4.6         4.9         5.4         6.2         7.4   
5          5.9         6.6         6.8         6.8         7.4         7.6   
6          NaN         NaN         NaN         NaN         NaN         NaN   
7          NaN         NaN         NaN         NaN         NaN         NaN   
8          NaN         NaN         NaN         NaN         NaN         NaN   
9          1.4         1.5         2.1         2.6         2.5        21.8   
10        10.1         9.9        10.0        10.5        11.0        10.8   
11        12.0        19.0        19.0        18.5        18.5        18.8   
12         5.9         6.2         6.9         9.7        10.1        10.1   
13         8.8        10.1         8.5        12.2        12.8        13.0   
14         NaN         NaN         NaN         NaN         NaN         NaN   
15         5.5         6.6         8.5         8.3         8.7        11.8   
16         6.1         5.1         5.6         7.9         7.7         7.6   
17         2.8         3.0         3.0         4.7         4.6         5.1   
18         5.7         5.9         7.2        10.4        10.9        10.6   
19         6.2         5.6         5.7         7.1         8.0         8.7   
20         0.9         0.8         0.8         0.1         3.2         3.9   
21         6.6         6.1         6.2         8.5         8.8        10.6   
22        10.5         9.4         9.3         9.5        10.2         6.6   
23         5.4         6.8         7.3         9.5        10.2         8.7   
24         3.0         3.8         3.4         4.2         4.9         3.8   
25         2.5         3.1         3.1         5.1         4.8         9.4   
26         4.7         5.0         6.2        10.7        10.5         7.2   
27         2.7         7.6         7.9         7.6         6.3         4.8   
28        13.7        13.7        13.7        18.1        18.1        10.6   
29         7.0         7.6         7.9        15.4        15.7        15.5   
30         7.3         7.3        10.0         9.2         9.8         9.3   
31        10.0        11.8        11.5        11.5        21.1        14.3   

    2014년 03분기  2014년 04분기  2015년 01분기  2015년 02분기  ...  2018년 02분기  \
0         12.6        12.7        13.5        12.7  ...        13.2   
1         10.4        10.8        12.0        10.2  ...        12.1   
2         12.6        14.1        13.4        11.1  ...        15.6   
3          6.0         4.3         4.8         5.7  ...         7.9   
4          8.7         9.3         5.4         7.6  ...         8.4   
5         12.9        11.4        10.5         9.2  ...         9.3   
6          NaN         NaN         NaN         NaN  ...         NaN   
7          NaN         NaN         NaN         NaN  ...         NaN   
8          NaN         NaN         NaN         NaN  ...         NaN   
9         21.0        31.1        30.7        20.8  ...        14.4   
10        10.8        10.1         9.4         8.1  ...        21.4   
11        19.6        20.3        18.9        18.3  ...        16.9   
12        10.3        10.1        10.6        11.0  ...         9.4   
13        11.1        11.3        14.3        14.2  ...        19.9   
14         NaN         NaN         NaN         NaN  ...         3.2   
15        14.0        11.4        12.0        12.7  ...         7.9   
16         7.5         6.3        10.0         8.1  ...        11.2   
17         8.5         9.2         6.8         6.6  ...         7.0   
18        10.7        10.8        10.4        11.5  ...         7.7   
19       

In [68]:
Non_Hyun_emp_rate = a.drop([6,7,8,9])
Non_Hyun_emp_rate

2013년 01분기  2013년 02분기  2013년 03분기  2013년 04분기  2014년 01분기  2014년 02분기  \
0          8.5         8.8         9.3        10.7        11.1        12.2   
1          6.2         6.4         6.8         8.4         8.9        10.4   
2          6.2         6.8         7.1         7.7         8.2        12.2   
3          4.6         4.9         5.1         7.0         7.8         7.1   
4          5.2         4.6         4.9         5.4         6.2         7.4   
5          5.9         6.6         6.8         6.8         7.4         7.6   
10        10.1         9.9        10.0        10.5        11.0        10.8   
11        12.0        19.0        19.0        18.5        18.5        18.8   
12         5.9         6.2         6.9         9.7        10.1        10.1   
13         8.8        10.1         8.5        12.2        12.8        13.0   
14         NaN         NaN         NaN         NaN         NaN         NaN   
15         5.5         6.6         8.5         8.3         8.7        11.8   
16         6.1         5.1         5.6         7.9         7.7         7.6   
17         2.8         3.0         3.0         4.7         4.6         5.1   
18         5.7         5.9         7.2        10.4        10.9        10.6   
19         6.2         5.6         5.7         7.1         8.0         8.7   
20         0.9         0.8         0.8         0.1         3.2         3.9   
21         6.6         6.1         6.2         8.5         8.8        10.6   
22        10.5         9.4         9.3         9.5        10.2         6.6   
23         5.4         6.8         7.3         9.5        10.2         8.7   
24         3.0         3.8         3.4         4.2         4.9         3.8   
25         2.5         3.1         3.1         5.1         4.8         9.4   
26         4.7         5.0         6.2        10.7        10.5         7.2   
27         2.7         7.6         7.9         7.6         6.3         4.8   
28        13.7        13.7        13.7        18.1        18.1        10.6   
29         7.0         7.6         7.9        15.4        15.7        15.5   
30         7.3         7.3        10.0         9.2         9.8         9.3   
31        10.0        11.8        11.5        11.5        21.1        14.3   

    2014년 03분기  2014년 04분기  2015년 01분기  2015년 02분기  ...  2018년 02분기  \
0         12.6        12.7        13.5        12.7  ...        13.2   
1         10.4        10.8        12.0        10.2  ...        12.1   
2         12.6        14.1        13.4        11.1  ...        15.6   
3          6.0         4.3         4.8         5.7  ...         7.9   
4          8.7         9.3         5.4         7.6  ...         8.4   
5         12.9        11.4        10.5         9.2  ...         9.3   
10        10.8        10.1         9.4         8.1  ...        21.4   
11        19.6        20.3        18.9        18.3  ...        16.9   
12        10.3        10.1        10.6        11.0  ...         9.4   
13        11.1        11.3        14.3        14.2  ...        19.9   
14         NaN         NaN         NaN         NaN  ...         3.2   
15        14.0        11.4        12.0        12.7  ...         7.9   
16         7.5         6.3        10.0         8.1  ...        11.2   
17         8.5         9.2         6.8         6.6  ...         7.0   
18        10.7        10.8        10.4        11.5  ...         7.7   
19         8.7         8.4         9.2         9.1  ...        10.8   
20         2.2         2.2         3.6         3.1  ...         6.4   
21        11.6        11.1        11.9        12.0  ...        11.0   
22         5.5         5.2         5.3         5.3  ...        15.9   
23         6.6         7.0         8.1         8.2  ...        15.3   
24         3.9         4.2         7.3         7.2  ...        23.0   
25        11.1        11.1         6.0         3.0  ...         6.2   
26         7.0         7.5        10.3        10.3  ...        15.0   
27         5.0         4.9         9.

In [69]:
Non_Hyun_emp_rate_train = Non_Hyun_emp_rate.drop(['2013년 01분기','2013년 02분기','2013년 03분기','2013년 04분기','2014년 01분기','2014년 02분기','2014년 03분기','2014년 04분기','2015년 01분기','2015년 02분기','2015년 03분기','2015년 04분기','2016년 01분기','2016년 02분기','2016년 03분기','2016년 04분기'], axis=1)

Non_Hyun_emp_rate_train_pred = Non_Hyun_emp_rate_train.iloc[10].to_numpy()

Non_Hyun_emp_rate_train_pred

array([14.2, 12. , 10.2,  8.5,  3.2,  3.2,  1.8,  2.6,  2.6,  2.6,  4.4,
        4.7,  4.7,  3.3,  2.4])

In [70]:
Non_Hyun_emp_rate_train = Non_Hyun_emp_rate_train.drop([14])

In [71]:
Non_Hyun_emp_rate_train = Non_Hyun_emp_rate_train.to_numpy()

In [72]:
Non_Hyun_emp_rate_train = np.transpose(Non_Hyun_emp_rate_train)

In [73]:
Non_Hyun_emp_rate_train

array([[11.5,  9.8, 11.8,  7.6,  7.3, 11.3, 11.1, 13.5,  6.3,  7.2,  7.2,
         6. ,  4.4,  5.9,  8.9,  6.5,  8.9, 12.5, 11.7, 22.8,  3.1,  6.5,
        13.8, 16.1,  4.4,  8.4,  8.9],
       [12.4, 11.3, 14.2,  6.8,  6.3,  8.2, 11.6, 13.6,  8.4, 18.1,  7.8,
        10.1,  8.3,  6.2, 10.9,  6.6, 12. , 11.4, 12.6, 21.2,  3.1,  8.4,
        15.9, 25.3,  4.8,  8.5, 13.4],
       [12. , 10.9, 13. ,  7.4,  6.7,  9.5, 11.4, 13.6,  8.6, 15.8,  6.7,
        11.1,  4.9,  7.3, 11.2,  6.6, 12.4, 11.8, 12. , 19.2,  3.8,  4.7,
        13. , 25.3,  4.9, 11.3, 14.3],
       [11.9, 10.5, 12.8,  7.2,  6.4,  9.6, 11. , 14.6,  8.9, 18.5,  6.7,
        11.7,  4.9,  7.2, 10.9,  8.8, 11.3, 11.7, 11.7, 20.3,  6.4,  6.7,
        14.3, 14.2,  4.8,  7.4, 15.8],
       [12.7, 11.9, 16.2,  7.5,  6.7,  9.9, 20.1, 14.6,  9.1, 18.6,  7.5,
        13. ,  7. ,  7.2, 10.4,  7.3, 10.5, 15. , 15.4, 23.2,  8.2, 10.5,
        12.7, 14.2, 12. , 12.5, 20.2],
       [13.2, 12.1, 15.6,  7.9,  8.4,  9.3, 21.4, 16.9,  9.4, 19.

In [74]:
reg = LinearRegression().fit(Non_Hyun_emp_rate_train, Non_Hyun_emp_rate_train_pred)

In [79]:
y_true = Non_Hyun_emp_rate_train_pred
y_pred = reg.predict(Non_Hyun_emp_rate_train)
y_pred
# mean_squared_error(y_true, y_pred)

array([14.2, 12. , 10.2,  8.5,  3.2,  3.2,  1.8,  2.6,  2.6,  2.6,  4.4,
        4.7,  4.7,  3.3,  2.4])

In [80]:
y_true

array([14.2, 12. , 10.2,  8.5,  3.2,  3.2,  1.8,  2.6,  2.6,  2.6,  4.4,
        4.7,  4.7,  3.3,  2.4])

In [77]:
mean_squared_error(y_true, y_pred)

5.451357547121034e-29

In [81]:
reg.coef_

array([ 0.13207241, -0.06543224, -0.34753629,  0.53092117, -0.08755839,
       -0.419267  , -0.10807964, -0.14507912, -0.11168674,  0.13253931,
       -0.31368896, -0.34296039, -0.43504022, -0.14611521, -0.23202926,
       -0.11045439, -0.35760748,  0.20854083,  0.0573721 ,  0.13765259,
        0.04321697,  0.00668649,  0.48194046,  0.28820413,  0.06045352,
       -0.26757083, -0.41064788])

In [82]:
# 2013 1분기 ~ 2016 4분기 논현역 공실률 

Non_Hyun_emp_rate_train = Non_Hyun_emp_rate[['2013년 01분기','2013년 02분기','2013년 03분기','2013년 04분기','2014년 01분기','2014년 02분기','2014년 03분기','2014년 04분기','2015년 01분기','2015년 02분기','2015년 03분기','2015년 04분기','2016년 01분기','2016년 02분기','2016년 03분기','2016년 04분기']]
Non_Hyun_emp_rate_train

2013년 01분기  2013년 02분기  2013년 03분기  2013년 04분기  2014년 01분기  2014년 02분기  \
0          8.5         8.8         9.3        10.7        11.1        12.2   
1          6.2         6.4         6.8         8.4         8.9        10.4   
2          6.2         6.8         7.1         7.7         8.2        12.2   
3          4.6         4.9         5.1         7.0         7.8         7.1   
4          5.2         4.6         4.9         5.4         6.2         7.4   
5          5.9         6.6         6.8         6.8         7.4         7.6   
10        10.1         9.9        10.0        10.5        11.0        10.8   
11        12.0        19.0        19.0        18.5        18.5        18.8   
12         5.9         6.2         6.9         9.7        10.1        10.1   
13         8.8        10.1         8.5        12.2        12.8        13.0   
14         NaN         NaN         NaN         NaN         NaN         NaN   
15         5.5         6.6         8.5         8.3         8.7        11.8   
16         6.1         5.1         5.6         7.9         7.7         7.6   
17         2.8         3.0         3.0         4.7         4.6         5.1   
18         5.7         5.9         7.2        10.4        10.9        10.6   
19         6.2         5.6         5.7         7.1         8.0         8.7   
20         0.9         0.8         0.8         0.1         3.2         3.9   
21         6.6         6.1         6.2         8.5         8.8        10.6   
22        10.5         9.4         9.3         9.5        10.2         6.6   
23         5.4         6.8         7.3         9.5        10.2         8.7   
24         3.0         3.8         3.4         4.2         4.9         3.8   
25         2.5         3.1         3.1         5.1         4.8         9.4   
26         4.7         5.0         6.2        10.7        10.5         7.2   
27         2.7         7.6         7.9         7.6         6.3         4.8   
28        13.7        13.7        13.7        18.1        18.1        10.6   
29         7.0         7.6         7.9        15.4        15.7        15.5   
30         7.3         7.3        10.0         9.2         9.8         9.3   
31        10.0        11.8        11.5        11.5        21.1        14.3   

    2014년 03분기  2014년 04분기  2015년 01분기  2015년 02분기  2015년 03분기  2015년 04분기  \
0         12.6        12.7        13.5        12.7        12.6        13.0   
1         10.4        10.8        12.0        10.2        10.1        10.2   
2         12.6        14.1        13.4        11.1         9.8        10.7   
3          6.0         4.3         4.8         5.7         5.5         8.2   
4          8.7         9.3         5.4         7.6         7.9         6.2   
5         12.9        11.4        10.5         9.2        10.5        14.6   
10        10.8        10.1         9.4         8.1         6.6         6.6   
11        19.6        20.3        18.9        18.3        13.4        17.2   
12        10.3        10.1        10.6        11.0        11.5        11.5   
13        11.1        11.3        14.3        14.2        18.5        22.6   
14         NaN         NaN         NaN         NaN         NaN         NaN   
15        14.0        11.4        12.0        12.7        12.8        13.3   
16         7.5         6.3        10.0         8.1         8.3         8.1   
17         8.5         9.2         6.8         6.6         5.0         5.0   
18        10.7        10.8        10.4        11.5        11.6        10.6   
19         8.7         8.4         9.2         9.1         9.3         9.4   
20         2.2         2.2         3.6         3.1         4.3         3.2   
21        11.6        11.1        11.9        12.0        11.0        11.4   
22         5.5         5.2         5.3         5.3         8.3         9.1   
23         6.6         7.0         8.1         8.2         9.0         8.3   
24         3.9         4.2         7.3         7.2        14.4        14.1   
25        11.1        11.

In [83]:
Non_Hyun_emp_rate_train_pred = Non_Hyun_emp_rate_train.iloc[10].to_numpy()
Non_Hyun_emp_rate_train_pred

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan])

In [84]:
Non_Hyun_emp_rate_train = Non_Hyun_emp_rate_train.drop([14])
Non_Hyun_emp_rate_train

2013년 01분기  2013년 02분기  2013년 03분기  2013년 04분기  2014년 01분기  2014년 02분기  \
0          8.5         8.8         9.3        10.7        11.1        12.2   
1          6.2         6.4         6.8         8.4         8.9        10.4   
2          6.2         6.8         7.1         7.7         8.2        12.2   
3          4.6         4.9         5.1         7.0         7.8         7.1   
4          5.2         4.6         4.9         5.4         6.2         7.4   
5          5.9         6.6         6.8         6.8         7.4         7.6   
10        10.1         9.9        10.0        10.5        11.0        10.8   
11        12.0        19.0        19.0        18.5        18.5        18.8   
12         5.9         6.2         6.9         9.7        10.1        10.1   
13         8.8        10.1         8.5        12.2        12.8        13.0   
15         5.5         6.6         8.5         8.3         8.7        11.8   
16         6.1         5.1         5.6         7.9         7.7         7.6   
17         2.8         3.0         3.0         4.7         4.6         5.1   
18         5.7         5.9         7.2        10.4        10.9        10.6   
19         6.2         5.6         5.7         7.1         8.0         8.7   
20         0.9         0.8         0.8         0.1         3.2         3.9   
21         6.6         6.1         6.2         8.5         8.8        10.6   
22        10.5         9.4         9.3         9.5        10.2         6.6   
23         5.4         6.8         7.3         9.5        10.2         8.7   
24         3.0         3.8         3.4         4.2         4.9         3.8   
25         2.5         3.1         3.1         5.1         4.8         9.4   
26         4.7         5.0         6.2        10.7        10.5         7.2   
27         2.7         7.6         7.9         7.6         6.3         4.8   
28        13.7        13.7        13.7        18.1        18.1        10.6   
29         7.0         7.6         7.9        15.4        15.7        15.5   
30         7.3         7.3        10.0         9.2         9.8         9.3   
31        10.0        11.8        11.5        11.5        21.1        14.3   

    2014년 03분기  2014년 04분기  2015년 01분기  2015년 02분기  2015년 03분기  2015년 04분기  \
0         12.6        12.7        13.5        12.7        12.6        13.0   
1         10.4        10.8        12.0        10.2        10.1        10.2   
2         12.6        14.1        13.4        11.1         9.8        10.7   
3          6.0         4.3         4.8         5.7         5.5         8.2   
4          8.7         9.3         5.4         7.6         7.9         6.2   
5         12.9        11.4        10.5         9.2        10.5        14.6   
10        10.8        10.1         9.4         8.1         6.6         6.6   
11        19.6        20.3        18.9        18.3        13.4        17.2   
12        10.3        10.1        10.6        11.0        11.5        11.5   
13        11.1        11.3        14.3        14.2        18.5        22.6   
15        14.0        11.4        12.0        12.7        12.8        13.3   
16         7.5         6.3        10.0         8.1         8.3         8.1   
17         8.5         9.2         6.8         6.6         5.0         5.0   
18        10.7        10.8        10.4        11.5        11.6        10.6   
19         8.7         8.4         9.2         9.1         9.3         9.4   
20         2.2         2.2         3.6         3.1         4.3         3.2   
21        11.6        11.1        11.9        12.0        11.0        11.4   
22         5.5         5.2         5.3         5.3         8.3         9.1   
23         6.6         7.0         8.1         8.2         9.0         8.3   
24         3.9         4.2         7.3         7.2        14.4        14.1   
25        11.1        11.1         6.0         3.0         3.0         3.3   
26         7.0         7.5        10.3        10.3        10.0        10.0   
27         5.0         4.

In [86]:
Non_Hyun_emp_rate_train = Non_Hyun_emp_rate_train.to_numpy() # .transpose(Non_Hyun_emp_rate_train)
Non_Hyun_emp_rate_train

array([[ 8.5,  8.8,  9.3, 10.7, 11.1, 12.2, 12.6, 12.7, 13.5, 12.7, 12.6,
        13. , 13.4, 13.4, 13. , 13. ],
       [ 6.2,  6.4,  6.8,  8.4,  8.9, 10.4, 10.4, 10.8, 12. , 10.2, 10.1,
        10.2, 10.1, 10.2,  9.4,  9.4],
       [ 6.2,  6.8,  7.1,  7.7,  8.2, 12.2, 12.6, 14.1, 13.4, 11.1,  9.8,
        10.7, 10.9, 11.5, 10.3, 10.4],
       [ 4.6,  4.9,  5.1,  7. ,  7.8,  7.1,  6. ,  4.3,  4.8,  5.7,  5.5,
         8.2,  8.6, 12.1, 11.6, 11.2],
       [ 5.2,  4.6,  4.9,  5.4,  6.2,  7.4,  8.7,  9.3,  5.4,  7.6,  7.9,
         6.2,  8.9,  9.4,  5.8,  6.6],
       [ 5.9,  6.6,  6.8,  6.8,  7.4,  7.6, 12.9, 11.4, 10.5,  9.2, 10.5,
        14.6, 15.5, 14.1, 13.3, 13. ],
       [10.1,  9.9, 10. , 10.5, 11. , 10.8, 10.8, 10.1,  9.4,  8.1,  6.6,
         6.6,  7.3,  7. ,  7.9,  6.5],
       [12. , 19. , 19. , 18.5, 18.5, 18.8, 19.6, 20.3, 18.9, 18.3, 13.4,
        17.2, 16. , 14.5, 10.1, 13.9],
       [ 5.9,  6.2,  6.9,  9.7, 10.1, 10.1, 10.3, 10.1, 10.6, 11. , 11.5,
        11.5, 10.4, 10

In [89]:
Non_Hyun_emp_rate_train.shape

(27, 16)

In [96]:
Non_Hyun_emp_rate_train = np.transpose(Non_Hyun_emp_rate_train)
Non_Hyun_emp_rate_train

array([[ 8.5,  6.2,  6.2,  4.6,  5.2,  5.9, 10.1, 12. ,  5.9,  8.8,  5.5,
         6.1,  2.8,  5.7,  6.2,  0.9,  6.6, 10.5,  5.4,  3. ,  2.5,  4.7,
         2.7, 13.7,  7. ,  7.3, 10. ],
       [ 8.8,  6.4,  6.8,  4.9,  4.6,  6.6,  9.9, 19. ,  6.2, 10.1,  6.6,
         5.1,  3. ,  5.9,  5.6,  0.8,  6.1,  9.4,  6.8,  3.8,  3.1,  5. ,
         7.6, 13.7,  7.6,  7.3, 11.8],
       [ 9.3,  6.8,  7.1,  5.1,  4.9,  6.8, 10. , 19. ,  6.9,  8.5,  8.5,
         5.6,  3. ,  7.2,  5.7,  0.8,  6.2,  9.3,  7.3,  3.4,  3.1,  6.2,
         7.9, 13.7,  7.9, 10. , 11.5],
       [10.7,  8.4,  7.7,  7. ,  5.4,  6.8, 10.5, 18.5,  9.7, 12.2,  8.3,
         7.9,  4.7, 10.4,  7.1,  0.1,  8.5,  9.5,  9.5,  4.2,  5.1, 10.7,
         7.6, 18.1, 15.4,  9.2, 11.5],
       [11.1,  8.9,  8.2,  7.8,  6.2,  7.4, 11. , 18.5, 10.1, 12.8,  8.7,
         7.7,  4.6, 10.9,  8. ,  3.2,  8.8, 10.2, 10.2,  4.9,  4.8, 10.5,
         6.3, 18.1, 15.7,  9.8, 21.1],
       [12.2, 10.4, 12.2,  7.1,  7.4,  7.6, 10.8, 18.8, 10.1, 13.

In [98]:
y_pred = reg.predict(Non_Hyun_emp_rate_train)
y_pred

array([11.13146472, 11.87099646, 10.009474  , 10.22462328,  4.96699756,
        0.29092648, -6.15760337, -6.25939016, -2.29344601, -0.20399076,
        4.89128048,  6.06584831,  2.32426906,  5.1982671 , 10.92551042,
        9.0100476 ])